apiVersion: v1
kind: Pod
metadata:
  name: hello-apparmor
  annotations:
    # Tell Kubernetes to apply the AppArmor profile "k8s-apparmor-example-deny-write".
    # Note that this is ignored if the Kubernetes node is not running version 1.4 or greater.

    # anotarile sunt informatii in plus pentru alte componente din ecosistem, este un mod de extindere
    # a funcitonalitatii, fara ele acest pod nu ar folosi politica de apparmor
    # cum putem folosi acest mecanism pentru noi
    container.apparmor.security.beta.kubernetes.io/hello: localhost/k8s-apparmor-example-deny-write
spec:
  containers:
  - name: hello
    image: busybox:1.28
    command: [ "sh", "-c", "echo 'Hello AppArmor!' && sleep 1h" ]
