apiVersion: v1
kind: Pod
metadata:
 name: cpu-demo
 annotations:
    keysight_t: "2"
spec:
 containers:
 - name: cpu-demo-ctr
   image: vish/stress
   resources:
     limits:
       cpu: 2500m
       memory: "256M"
     requests:
       cpu: 2500m
       memory: "256M"
   args:
   - -cpus
   - "2"
